# Extends the board Zephyr already ships as
# boards/makerdiary/nrf52840_mdk_usb_dongle, adding the `zmk` variant that
# ZMK's build system expects. Build target: nrf52840_mdk_usb_dongle//zmk
board:
  extend: nrf52840_mdk_usb_dongle
  variants:
    - name: zmk
      qualifier: nrf52840
